### ISSUE TITLE
Can't get hot-reload to work for remote server with private IP

### ISSUE THREAD

**Issue by pwwolf** [webpack/webpack-dev-server#205]
I have a remote dev server with a private IP which I use to run webpack.  The machine is accessible from a public IP/host which is different from the IP that the server binds to.

If I specify --host 0.0.0.0, I can hit the server initially, but the reload doesn't work because my browser is trying to make a connection to "http://0.0.0.0:8080/socket.io/...".  Alternatively I've tried setting --host to my public IP, but it fails to start because it can't bind to that IP.

Is there any way to make the socket.io relative to whatever URL is in the browser rather than copying the --host value directly?... or just looking at document.location.origin

**Comment by sokra** [comment]
If you don't use inline mode `--inline` you can specify the remote path in the query parameter of the client reference `webpack-dev-server/client?http://url:8080`

**Comment by cdaringe** [comment]
hi @sokra, thanks for the great project.  can you add a bit more clarification?  this would be helpful to me as well!  _which_ client reference?  and can you confirm the proper query kv pair?  i assume my client needs to be uri encoded as well?

**Comment by aaronjensen** [comment]
I just struggled w/ this for a while, and this is what I came up with:

```
inline: false
```

```
entries: ['webpack/hot/only-dev-server', 'your-entry.js']
```

In your index.html:
```html
    <script src="bundle.js"></script>
    <script>
      var devServer = document.createElement('script');
      devServer.setAttribute('src', 'http://' + window.location.host + '/webpack-dev-server.js');
      document.body.appendChild(devServer);
    </script>
```

This seems to work regardless of where you access it from...

**Comment by kentor** [comment]
@aaronjensen did you get hot reloading to work? Even with your set up the page always refreshes because it can't find the manifest file. See https://github.com/webpack/webpack-dev-server/issues/262

**Comment by aaronjensen** [comment]
@kentor yes, it works for me. I had to do something like `window.location.host.replace(':4000', ':4001')` because I was proxying through browser-sync, but other than that it works great.

**Comment by eteeselink** [comment]
Note: this was fixed in this PR: https://github.com/webpack/webpack-dev-server/pull/263/files. the latest release on NPM includes this fix. It does exactly what @pwwolf suggested:

> Is there any way to make the socket.io relative to whatever URL is in the browser rather than copying the --host value directly?... or just looking at document.location.origin

but only if the host passed was `"0.0.0.0"`.

**Comment by eteeselink** [comment]
(cc @sokra I therefore believe this issue can be closed)

**Comment by vaiRk** [comment]
I'm still seeing this issue with the latest version of webpack (1.12.11) and webpack-dev-server (1.14.1).

Can't reach /sockjs-node. I'm not using inline mode and I'm setting 0.0.0.0 via query param on the client.

**Comment by SpaceK33z** [comment]
Closing this issue because it was solved a while ago (see @eteeselink's comment).
