### ISSUE TITLE
Error: Cannot find module 'webpack-cli/bin/config-yargs' when use v5

### ISSUE THREAD

**Issue by teabyii** [webpack/webpack-dev-server#2424]
https://github.com/webpack/webpack-dev-server/blob/c9e9178a4882e414a6b9616baa35e8dbf7b2dd75/bin/webpack-dev-server.js#L61

`webpack-cli/bin/` no longer exists as of (https://github.com/webpack/webpack-cli/commit/82407e5e1fee2ce7e8dd4cfa9596b99ed0cde4fc). This is a blocker for at least `webpack-cli@4.0.0-alpha-5`. Is there a workaround...?

_Originally posted by @JoshuaKGoldberg in https://github.com/webpack/webpack-dev-server/issues/2239#issuecomment-539163568_

**Comment by evilebottnawi** [comment]
Yes please use `webpack serve` for `4` version to run webpack dev server, we will remove own binaries in next version, feel free to leave feedback if something doesn't work for `webpack serve`

**Comment by teabyii** [comment]
![image](https://user-images.githubusercontent.com/4496552/73641625-43426c80-46ab-11ea-88ce-c60dfae4ea5e.png)
I used `webpack serve`，but it didn't work.
This is my package dependencies:

```json
  "devDependencies": {
    "webpack": "^5.0.0-beta.12",
    "webpack-cli": "^4.0.0-beta.1",
    "webpack-dev-server": "^3.10.2"
  }
```

**Comment by evilebottnawi** [comment]
Oh, should be work, can you open issue in webpack-cli?

**Comment by teabyii** [comment]
OK，I will.

**Comment by Vadimkin448** [comment]
> https://github.com/webpack/webpack-dev-server/blob/c9e9178a4882e414a6b9616baa35e8dbf7b2dd75/bin/webpack-dev-server.js#L61
> 
> `webpack-cli/bin/` no longer exists as of ([webpack/webpack-cli@82407e5](https://github.com/webpack/webpack-cli/commit/82407e5e1fee2ce7e8dd4cfa9596b99ed0cde4fc)). This is a blocker for at least `webpack-cli@4.0.0-alpha-5`. Is there a workaround...?
> 
> _Originally posted by @JoshuaKGoldberg in [#2239 (comment)](https://github.com/webpack/webpack-dev-server/issues/2239#issuecomment-539163568)_

**Comment by richburdon** [comment]
Same problem here -- any update since Feb 3?

```
    "webpack": "^4.41.2",
    "webpack-bundle-analyzer": "^3.6.0",
    "webpack-cli": "^3.3.11",
    "webpack-dev-server": "^3.11.0",
    "webpack-merge": "^4.2.2",
    "webpack-version-file-plugin": "^0.4.0",
```

**Comment by belauzas** [comment]
Same problem for me
```
"devDependencies": {
    "@webpack-cli/init": "^0.3.0",
    "css-loader": "^3.6.0",
    "html-webpack-plugin": "^4.3.0",
    "node-sass": "^4.14.1",
    "sass-loader": "^8.0.2",
    "style-loader": "^1.2.1",
    "webpack": "^4.43.0",
    "webpack-cli": "^4.0.0-beta.8",
    "webpack-dev-server": "^3.11.0",
    "webpack-merge": "^4.2.2"
  }
```
What does works?
`"start": "webpack --config webpack.dev.js",`
What does not work?
`"start": "webpack-dev-server --config webpack.dev.js",`.

**Comment by ylemkimon** [comment]
Try `npm install --save-dev @webpack-cli/serve@beta` or `yarn add -D @webpack-cli/serve@beta`.

**Comment by koistya** [comment]
```
$ yarn add @webpack-cli/serve@beta -D
$ yarn webpack-cli serve

[webpack-cli] The command moved into a separate package: @webpack-cli/serve

(node:12806) [MODULE_NOT_FOUND] Error: @webpack-cli/package-utils tried to access cross-spawn, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
? Would you like to install @webpack-cli/serve? (That will run npm install -D @webpack-cli/serve) (Y/n) › true
```

**Comment by evilebottnawi** [comment]
@koistya do you use yarn?

**Comment by merceyz** [comment]
That specific issue was fixed in https://github.com/webpack/webpack-cli/pull/1376 5 months ago, but it hasn't been released yet

**Comment by evilebottnawi** [comment]
@merceyz release `webpack-cli` will be on this week, you even no need to install `@webpack-cli/serve`, because it will be out of box, just run `webpack serve`

**Comment by bahtou** [comment]
Any updates on this?


```json
"@webpack-cli/serve": "^0.2.0",
"webpack": "^5.0.0-beta.29",
"webpack-cli": "^4.0.0-beta.8",
"webpack-dev-server": "^3.11.0"
```

`> webpack-cli serve --config .webpack/index.js`

```bash
[webpack-cli] The command moved into a separate package: @webpack-cli/serve

? Would you like to install @webpack-cli/serve? (That will run npm install -D @webpack-cli/serve) (Y/n) › true
```

**Comment by ylemkimon** [comment]
@bahtou You need to install the beta version of `@webpack-cli/serve`, see https://github.com/webpack/webpack-dev-server/issues/2424#issuecomment-659982961.

**Comment by bahtou** [comment]
@ylemkimon 
```json
"@webpack-cli/serve": "^1.0.1-alpha.5",
"webpack": "^5.0.0-beta.29",
"webpack-cli": "^4.0.0-beta.8",
"webpack-dev-server": "^3.11.0",
```

`> webpack-cli serve --config .webpack/index.js --mode development`

```bash
Module not found: Error: Can't resolve './index.js'
```

If I move `index.js` out of the `.webpack` directory into root the file is then resolved, but not inside another folder.

**Comment by evilebottnawi** [comment]
@bahtou fixed in webpack-cli, release will be today/tomorrow, feel free to feedback after new release

**Comment by mnjit20** [comment]
any update on this.

**Comment by NikoGrano** [comment]
@evilebottnawi Could you specify the release? I can still reproduce this issue.

I have been also trying `4.0.0-rc.0` on `webpack-cli` released 13 hours ago.
Now I have following:
```
    "webpack": "5.0.0-rc.0",
    "webpack-cli": "4.0.0-beta.9",
    "webpack-dev-server": "^3.11",
    "@webpack-cli/serve": "^1.0.1-rc.0"
```

I just wonder why this have been happening lately a lot with different versions...

**Comment by evilebottnawi** [comment]
@NicholasBoll What do you mean?

**Comment by NikoGrano** [comment]
> @\bahtou fixed in webpack-cli, release will be today/tomorrow, feel free to feedback after new release

@evilebottnawi I think you pinged wrong person. I mean, you said there is release which might be fixing this. That's is the reason I asked what release you mean, due I can reproduce this issue pretty much with all releases.

**Comment by evilebottnawi** [comment]
@NikoGrano How you run webpack-dev-server?

**Comment by NikoGrano** [comment]
@evilebottnawi Thanks for you answer.
I'm running it via `npm run dev` which resolves into `webpack-dev-server`.

My webpack.config.js contains about following:
```js
module.exports = {
    entry: './src/index.tsx',
    devtool: 'inline-source-map',
    output: {
        path: path.resolve(__dirname, '../htdocs/'),
        filename: 'index.js'
    },
    devServer: {
        inline: true,
        port: 9999,
        contentBase: './src',
        proxy: {
            ...
        }
    },
    module: {
        rules: [
            { test: /\.js$/, exclude: /node_modules/,  loader: 'babel-loader', options: { presets: ['@babel/preset-env', '@babel/preset-react'] } },
            { test: /\.tsx?$/, loader: 'ts-loader' },
        ]
    },
    resolve: {
        extensions: ['.wasm', '.mjs', '.js', '.jsx', '.ts', '.tsx', '.json'],
    },
    plugins: [
        // filled in webpack.production.config.js
    ]
};

```

**Comment by evilebottnawi** [comment]
You need to use `webpack serve`

**Comment by NikoGrano** [comment]
@evilebottnawi Just reporting results: It works! **Thank you!**

**Comment by please-rewrite** [comment]
@evilebottnawi thank you. This really needs to be mentioned in the migrate to webpack 5 doc that is out there

**Comment by bahtou** [comment]
@evilebottnawi   I'm getting this error when I updated:
```json
"@webpack-cli/serve": "^1.0.1-rc.0",
"webpack": "^5.0.0-rc.0",
"webpack-cli": "^4.0.0-rc.0",
"webpack-dev-server": "^3.11.0",
```

```bash
> webpack server --config .webpack/index.js --mode development
[webpack-cli] TypeError: Cannot read property 'length' of undefined
```

**Comment by evilebottnawi** [comment]
@bahtou please create reproducible test repo and open an issue in webpack-cli, thanks!

**Comment by galbeiroc** [comment]
I have the same issue

**Comment by evilebottnawi** [comment]
@bahtou only on windows?

**Comment by galbeiroc** [comment]
> @bahtou only on windows?

Windows 10

  "devDependencies": {
    "@webpack-cli/serve": "^1.0.1",
    "clean-webpack-plugin": "^3.0.0",
    "html-webpack-plugin": "^4.5.0",
    "webpack": "^5.0.0",
    "webpack-cli": "^4.0.0",
    "webpack-dev-server": "^3.11.0"
  },

    "start": "webpack-dev-server"

Error: Cannot find module 'webpack-cli/bin/config-yargs'

**Comment by evilebottnawi** [comment]
@galbeiroc Do you read my answer? Please use `webpack serve` to run webpack dev server

**Comment by galbeiroc** [comment]
> @galbeiroc Do you read my answer? Please use `webpack serve` to run webpack dev server

it works succesfully

webpack 5.0.0 compiled successfully in 430 ms

`"dev": "webpack serve"`

Thanks !! @evilebottnawi

**Comment by bahtou** [comment]
@evilebottnawi I have not tested on windows only OSX

**Comment by infime** [comment]
Will `webpack serve` support eventually the same cli options that webpack-dev-server currently does?

**Comment by evilebottnawi** [comment]
No, only basic option, you can use the config for complex options, what do you need? Which options?

**Comment by ansh47** [comment]
Received the following error on running "npm start":
Error: Cannot find module 'webpack-cli/bin/config-yargs'

package.json file
`{
  "name": "understanding-webpack",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "webpack-dev-server",
    "build:prod": "webpack --config webpack.config.prod.js"
  },
  "author": "",
  "license": "ISC",
  "browsersList": "> 1%, last 2 versions",
  "devDependencies": {
    "@babel/core": "^7.11.6",
    "@babel/plugin-proposal-class-properties": "^7.10.4",
    "@babel/preset-env": "^7.11.5",
    "@babel/preset-react": "^7.10.4",
    "@babel/preset-stage-2": "^7.8.3",
    "autoprefixer": "^10.0.1",
    "babel-loader": "^8.1.0",
    "css-loader": "^4.3.0",
    "file-loader": "^6.1.1",
    "html-webpack-plugin": "^4.5.0",
    "postcss-loader": "^4.0.4",
    "style-loader": "^2.0.0",
    "url-loader": "^4.1.1",
    "webpack": "^5.0.0",
    "webpack-cli": "^4.0.0",
    "webpack-dev-server": "^3.11.0"
  },
  "dependencies": {
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-router-dom": "^5.2.0"
  }
}
`

**Comment by infime** [comment]
@evilebottnawi I was using `overlay`, `https` and `cert`/ `key` in several different invocations for different scenarios. Letting `webpack serve --help` show the available options would be helpful as well.

**Comment by evilebottnawi** [comment]
@infime we consider this, thanks for feedback

**Comment by adi518** [comment]
This happened to me when using Webpack 4 with Webpack CLI version 4. I downgraded to version 3 and all it's working again. If you are still on Webpack 4, downgrade for the time being, unless there's no backward compatibility. It does seem more like a bug in backward compatibility, because I haven't seen warnings for a wrong peer dependency (`webpack`) of `webpack-cli`.

**Comment by lewislbr** [comment]
So is `webpack-dev-server` not needed when using webpack 5?

**Comment by adi518** [comment]
How was my comment spam? how rude. 👎 This thread has an answer that doesn't correspond to the docs. The `webpack serve` command doesn't come up when searching the docs of Webpack 4/5.

**Comment by ylemkimon** [comment]
@adi518 https://github.com/webpack/webpack-cli#commands

**Comment by adi518** [comment]
Thanksץ For such a mainstream tool, it should be in the docs.

**Comment by bino98** [comment]
https://github.com/webpack/webpack-dev-server/issues/2770#issuecomment-709209686

I wrote a comment in this issue.
I don't think this behavior will load the webpack config.

wrong?

**Comment by evilebottnawi** [comment]
https://github.com/webpack/webpack-cli/issues/1948

**Comment by Jaffsterz** [comment]
If I use "webpack serve" instead of "webpack-dev-server" then my "--config" file option is being ignored.
What is the equivalent for providing the config file?

**Comment by Yaolegol** [comment]
In my case the solution was just use previous versions - 

    "webpack": "^4.44.1",
    "webpack-cli": "^3.3.12",
    "webpack-dev-server": "^3.11.0"

**Comment by Suwings** [comment]
In `v5.1.3` , it can be started by using the `webpack serve` command, but it still requires `webpack-dev-server` dependency.

```js
"webpack": "^5.1.3",
"webpack-cli": "^4.1.0",
"webpack-dev-server": "^3.11.0",
```

It has been put into use without any problems.

**Comment by cq-ubaid-khan** [comment]
./node_modules/.bin/webpack-dev-server --mode development --open --progress --hot --inline

**Comment by andresfgz** [comment]
solution: 
npm install webpack@4.32.2 --save-dev --save-exact
npm install webpack-cli@3.3.2 --save-dev --save-exact
npm install webpack-dev-server@3.5.1 --save-dev --save-exact

**Comment by evilebottnawi** [comment]
@andresfgz It is not solution

**Comment by epicoding95** [comment]
I'm also having the same problems as @Suwings where my config file doesn't get looked at when using webpack serve . Has anyone found a solution yet?

**Comment by MadOgre** [comment]
> In `v5.1.3` , it can be started by using the `webpack serve` command, but it still requires `webpack-dev-server` dependency.
> 
> ```js
> "webpack": "^5.1.3",
> "webpack-cli": "^4.1.0",
> "webpack-dev-server": "^3.11.0",
> ```
> 
> It has been put into use without any problems.

Why would this be marked as spam. This is actually the solution for right now until a better one presents itself. It seems like someone is trying to force a new version before support has caught up

**Comment by MadOgre** [comment]
> In my case the solution was just use previous versions -
> 
> ```
> "webpack": "^4.44.1",
> "webpack-cli": "^3.3.12",
> "webpack-dev-server": "^3.11.0"
> ```

Why would this be marked as spam. This is actually the solution for right now until a better one presents itself. It seems like someone is trying to force a new version before support has caught up

**Comment by evilebottnawi** [comment]
SOLUTION - https://github.com/webpack/webpack-cli/issues/1948#issuecomment-708939567

**Comment by epicoding95** [comment]
im still getting `[webpack-cli] Error: byDependency and undefined for a single property is not supported`,  any ideas ?

**Comment by evilebottnawi** [comment]
@epicoding95 something wrong with you configuration, this problem not related to your

**Comment by Nethanos** [comment]
I don't know if you are the same team that maintains webpack-dev-server but wouldn't be cool if there is a post or article exposing this change? From my point of view this is some kind of breaking change... Don't you agree? Maybe a commentary on the changelog should be enough.

**Comment by iztokf** [comment]
this is totally frustrating :( tried all suggestions/hacks from all opened issues, but nothing works..

```
webpack serve --config webpack.config.dev.js

internal/modules/cjs/loader.js:638
    throw err;
    ^
Error: Cannot find module 'webpack-cli/bin/config-yargs'

```

```
    "webpack": "^5.1.3",
    "webpack-cli": "^4.1.0",
    "webpack-dev-server": "^3.11.0"
```
am i missing something? please, help!

**Comment by evilebottnawi** [comment]
Please use `webpack serve` instead of using `webpack-dev-server` in `package.json`, it was answered a lot of time, but because each every time no wants to read but just writes the answer constantly disappears

**Comment by sacummings91** [comment]
@evilebottnawi I think the issue is we do not get the same functionality with just using `webpack serve` and there doesn't seem to be any explanation with how to get it working in the same way. Are you going to provide some official documentation of these changes?

**Comment by iztokf** [comment]
> Please use `webpack serve` instead of using `webpack-dev-server` in `package.json`

i was trying to run it from cli/console, which still don't work btw; yes, if i run it as package.json script (npm run-script ...) than it's ok; thanks!

**Comment by lornally** [comment]
this is ok: 
`   "webpack": "^5.3.2",
    "webpack-cli": "^3.3.10",
		"webpack-dev-server": "^3.11.0"  `	

but this is wrong: 
`		"webpack": "^5.3.2",
		"webpack-cli": "^4.1.0",
		"webpack-dev-server": "^3.11.0"

`

**Comment by jkanchelov** [comment]
@evilebottnawi is this a temporary solution and if not could you give me an example of how to live-reload on change with the webpack serve

**Comment by ferneybaron** [comment]
Hello 👋.
To fix it just do 2 things.
1. Install 
    npm i webpack-cli @webpack-cli/init
2.  add this to your package.json
     "scripts": {
          "start": "webpack-cli serve --mode development"
     },

done!

**Comment by sacummings91** [comment]
This seems like a lot of hoops to jump through compared to just doing `webpack-dev-server` which used to work

**Comment by wwn** [comment]
How do I use it together with babel. Replace this line:
"start:dev": "babel-node ./node_modules/webpack-dev-server/bin/webpack-dev-server --open"?

...tried with webpack-cli/bin/cli.... without success

**Comment by SevlaMare** [comment]
```
"webpack": "^4.44.2",
"webpack-cli": "^4.2.0",
"webpack-dev-server": "^3.11.0"
```

using 
`    "start": "npx webpack-dev-server --host 0.0.0.0 --port 7000",`

works on windows, crash on ubuntu 18:

`Error: Cannot find module 'webpack-cli/bin/config-yargs'`

**Comment by SevlaMare** [comment]
```
"webpack": "^4.44.2",
"webpack-cli": "^4.2.0",
"webpack-dev-server": "^3.11.0"
```

using 
`    "start": "npx webpack-dev-server --host 0.0.0.0 --port 7000",`

works on windows (node 14), 
crash on ubuntu 18 (node 12)
using yarn or npm get the same error:

`Error: Cannot find module 'webpack-cli/bin/config-yargs'`

works on ubuntu after downgrade to:
    "webpack-cli": "^3.3.12"

**Comment by PeculiarCode** [comment]
> 你好 👋。
> 要解决它，只需做两件事。
> 
> 1. 安装
>    npm i webpack-cli @ webpack-cli / init
> 2. 将此添加到您的package.json 
>    “ scripts”：{ 
>    “ start”：“ webpack-cli serve --mode development” 
>    }，
> 
> 完成！
perfect

**Comment by PeculiarCode** [comment]
> Hello 👋.
> To fix it just do 2 things.
> 
> 1. Install
>    npm i webpack-cli @webpack-cli/init
> 2. add this to your package.json
>    "scripts": {
>    "start": "webpack-cli serve --mode development"
>    },
> 
> done!

perfect

**Comment by alexander-akait** [comment]
Fixed in `webpack-dev-server@4-beta.0`

**Comment by Jaffsterz** [comment]
Could someone explain what "webpack serve" is actually doing as a command, as opposed to "webpack-dev-server"? It might help people understand why they now have to do this.

Is it running the "webpack-serve" server instead of the "webpacl-dev-server" one? (if so, how does it work without that dependency being installed?)

I found plenty of reports sayng webpack-dev-server is only in maintenance and that people should use webpack-serve instead, but that doesn't seem to be the case here as web-pack-dev server now appears to have a major new version in beta?

This is all quite confusing for people I think! :(

**Comment by AstroProjection** [comment]
It didn't work for me until I specified  the 'contentBase' and 'port' property of the devServer and ran the command 'webpack serve --config ./webpack.config.js'

**Comment by amir4z** [comment]
webpack-dev-server/bin/webpack-dev-server.js

Line 61 in c9e9178

 configYargsPath = 'webpack-cli/bin/config-yargs';
