### ISSUE TITLE
Webpack-dev-server log when it shouldn't

### ISSUE THREAD

**Issue by jimblue** [webpack/webpack-dev-server#2718]
- Operating System: macOS Catalina 10.15.6
- Node Version: 12.18.3
- NPM Version: 6.14.8
- webpack Version: 4.44.1
- webpack-dev-server Version: 3.11.0
- Browser: Google Chrome 84.0.4147.135

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
devServer {
  noInfo: true,
  quiet: true,
  stats: 'none',
  clientLogLevel: 'none',
}
```

### Expected Behavior

With the above config `weback-dev-server` shouldn't output anything in the console.

### Actual Behavior

With the above config `weback-dev-server` output the following in the console:

```bash
｢wds｣: Project is running at https://mywebsite.test:3001/
｢wds｣: webpack output is served from undefined
```

### How can we reproduce the behavior?

Use the above config and run `weback-dev-server`

**Comment by evilebottnawi** [comment]
Fixed in v4

**Comment by jimblue** [comment]
cool tks @evilebottnawi

**Comment by jimblue** [comment]
Just update to `Webpack 5.1.0` and `webpack-dev-server 3.11.0` and I still have the logs.

**Comment by evilebottnawi** [comment]
@jimblue because webpack-dev-server doesn't have update?

**Comment by jimblue** [comment]
oh sorry I miss read so I must wait for V4 ! Tks for your answer 😄
