### ISSUE TITLE
load hot update chunk fail when use module fedration

### ISSUE THREAD

**Issue by shaodahong** [webpack/webpack-dev-server#2906]
- Operating System:OSX
- Node Version:12.16.1
- NPM Version:6.13.4
- webpack Version:5.9.0
- webpack-dev-server Version:4.0.0-beta.0
- Browser:Chorme latest

- [x] This is a **bug**
- [ ] This is a **modification** request

### Expected Behavior
hmr normal

### Actual Behavior
change code and hmr fail

error log

```bash 
[HMR] Waiting for update signal from WDS...
2VM27 log.js:1 [webpack-dev-server] Hot Module Replacement enabled.
4VM27 log.js:1 [webpack-dev-server] App updated. Recompiling...
VM27 log.js:1 [webpack-dev-server] App hot update...
VM47 log.js:24 [HMR] Checking for updates on the server...
log.js:1 [webpack-dev-server] App hot update...
log.js:24 [HMR] Checking for updates on the server...
VM47 log.js:26 [HMR] Update failed: ChunkLoadError: Loading hot update chunk main failed.
(missing: http://127.0.0.1:3001/main.e682c95faccadaebc4b8.hot-update.js)
    at http://127.0.0.1:3001/main.js:1570:26
    at new Promise (<anonymous>)
    at loadUpdateChunk (http://127.0.0.1:3001/main.js:1565:20)
    at http://127.0.0.1:3001/main.js:1994:29
    at Array.forEach (<anonymous>)
    at Object.__webpack_require__.hmrC.jsonp (http://127.0.0.1:3001/main.js:1989:22)
    at http://127.0.0.1:3001/main.js:1190:45
    at Array.reduce (<anonymous>)
    at http://127.0.0.1:3001/main.js:1186:53
module.exports @ VM47 log.js:26
eval @ VM46 dev-server.js:46
Promise.catch (async)
check @ VM46 dev-server.js:36
eval @ VM46 dev-server.js:55
emit @ VM49 events.js:153
reloadApp @ VM37 reloadApp.js:23
ok @ VM22 index.js:123
eval @ VM24 socket.js:44
client.onmessage @ VM25 WebsocketClient.js:67
log.js:24 [HMR] Updated modules:
log.js:24 [HMR]  - ./src/App.jsx
log.js:24 
```

### For Bugs; How can we reproduce the behavior?

Report res: https://github.com/shaodahong/module-federation-hmr-report

1, clone respo
2. `yarn` and `yarn start`
3, change `app.jsx` some code and view devtool console log

**Comment by alexander-akait** [comment]
module fedration is not supported and I think will be not in near future, but you can send a PR

**Comment by csvan** [comment]
@shaodahong what if you use the normal reload rather than HMR?

**Comment by csvan** [comment]
@alexander-akait roughly speaking, what would we need to change in order to get module federation supported?

**Comment by csvan** [comment]
Some clues here: https://github.com/webpack/webpack-dev-server/issues/2692

**Comment by alexander-akait** [comment]
Yep, we need to fix multiple entry points, first

**Comment by shaodahong** [comment]
> what if you use the normal reload rather than HMR?

@csvan if use live reload, now it's fine

And fix `hmr`, the difficulty is  `moduleFedration` dynamic create`remoteEntry.js`, seem `webpack-dev-server` can not resolve, maybe need to `webpack` to resolve

**Comment by csvan** [comment]
@alexander-akait would using the plugin mentioned here solve this issue? It only seems to work for Webpack 5, but that's ok since it is the sole target of the new dev server.

https://github.com/webpack/webpack-dev-server/issues/2692#issuecomment-682439552

**Comment by alexander-akait** [comment]
Better solution here https://github.com/webpack/webpack-dev-server/pull/2920/files, but I need time to rewrite tests :disappointed:

**Comment by alexander-akait** [comment]
It should fix all cases with entries

**Comment by peakcool** [comment]
So how will this problem be solved in the end?

**Comment by alexander-akait** [comment]
@peakcool will be great if you test it, should be yes

**Comment by shaodahong** [comment]
I try again, still broken.

webpack-dev-server: `4.0.0-beta.1`
webpack: `5.28.0`

**Comment by alexander-akait** [comment]
Yep, HMR is not supported for Module federation by webpack right now, close in favor https://github.com/webpack/webpack/issues/11182, nothing to fix here, sorry
