### ISSUE TITLE
｢wds｣: webpack output is served from undefined

### ISSUE THREAD

**Issue by boojum** [webpack/webpack-dev-server#2947]
- Operating System: Linux
- Node Version: 15.5.0
- NPM Version: 7.3.0
- webpack Version: 5.9.0
- webpack-dev-server Version: 3.11.0
- Browser: latest stable Chrome / Firefox

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

The example repo can be found [here](https://github.com/boojum/react-base). For quick reference, `webpack` config is as follows:

```js
// webpack.config.js

const path = require("path");
const { merge } = require("webpack-merge");
const parts = require("./webpack.parts");

const commonConfig = merge([
  {
    entry: path.join(__dirname, "/src/index.jsx"),
  },
  {
    output: {
      filename: "[name].bundle.js",
      path: path.join(__dirname, "/dist"),
    },
  },
  {
    resolve: {
      extensions: [".js", ".jsx"],
    },
  },
  parts.clean(),
  parts.page(),
  parts.extractCSS(),
  parts.loadImages({ limit: 15000 }),
  parts.loadSvg(),
  parts.loadJavaScript(),
]);

const productionConfig = merge([
  {
    output: {
      chunkFilename: "[name].[contenthash].js",
      filename: "[name].[contenthash].js",
      assetModuleFilename: "[name].[contenthash][ext][query]",
    },
  },
  parts.minifyJavaScript(),
  parts.generateSourceMaps({ type: "source-map" }),
]);

const developmentConfig = merge([
  parts.generateSourceMaps({ type: "source-map" }),
  parts.devServer(),
]);

module.exports = (env, argv) => {
  switch (argv.mode) {
    case "production":
      return merge(commonConfig, productionConfig, { mode: argv.mode });
    case "development":
      return merge(commonConfig, developmentConfig), { mode: argv.mode };
    default:
      throw new Error(`Trying to use an unknown mode, ${argv.mode}`);
  }
};
```

```js
// webpack.parts.js

const path = require("path");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const { CleanWebpackPlugin } = require("clean-webpack-plugin");
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const TerserPlugin = require("terser-webpack-plugin");

// Common

exports.clean = () => ({ plugins: [new CleanWebpackPlugin()] });

exports.page = () => ({
  plugins: [
    new HtmlWebpackPlugin({
      cache: false,
      title: "react base",
      favicon: "src/assets/favicon.ico",
      template: "src/assets/static/index.html",
    }),
  ],
});

exports.extractCSS = ({ options = {} } = {}) => {
  return {
    module: {
      rules: [
        {
          test: /\.css$/,
          include: /\.module\.css$/,
          use: [
            { loader: MiniCssExtractPlugin.loader, options },
            {
              loader: "css-loader",
              options: {
                importLoaders: 1,
                modules: {
                  localIdentName: "[name]__[local]--[hash:base64:5]",
                },
              },
            },
            "postcss-loader",
          ],
        },
        {
          test: /\.css$/,
          exclude: /\.module\.css$/,
          use: [
            { loader: MiniCssExtractPlugin.loader, options },
            {
              loader: "css-loader",
              options: {
                importLoaders: 1,
              },
            },
            "postcss-loader",
          ],
        },
      ],
    },
    plugins: [
      new MiniCssExtractPlugin({
        filename: "[name].[contenthash].css",
      }),
    ],
  };
};

exports.loadImages = ({ limit } = {}) => ({
  module: {
    rules: [
      {
        test: /\.(png|jpg|jpeg)$/,
        type: "asset",
        parser: { dataUrlCondition: { maxSize: limit } },
      },
    ],
  },
});

exports.loadSvg = () => ({
  module: {
    rules: [
      {
        test: /\.svg$/,
        use: [
          {
            loader: "@svgr/webpack",
          },
        ],
      },
    ],
  },
});

exports.loadJavaScript = () => ({
  module: {
    rules: [
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        include: path.join(__dirname, "/src"),
        use: [
          {
            loader: "babel-loader",
            options: {
              configFile: path.join(__dirname + "/babel.config.js"),
            },
          },
        ],
      },
    ],
  },
});

// Development
exports.devServer = () => ({
  devServer: {
    contentBase: path.join(__dirname, "/dist"),
  },
});

// Production

exports.minifyJavaScript = () => ({
  optimization: { minimizer: [new TerserPlugin()] },
});

exports.generateSourceMaps = ({ type }) => ({ devtool: type });
```

### Expected Behavior
`npm start` will start `webpack-dev-server` without any errors.

### Actual Behavior
```sh
> NODE_ENV=development webpack serve --mode development

ℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from undefined
ℹ ｢wds｣: Content not from webpack is served from /home/boojum/Projects/foobar
✖ ｢wdm｣: asset main.js 644 bytes [emitted] (name: main)

ERROR in main
Module not found: Error: Can't resolve './src' in '/home/boojum/Projects/foobar'

ERROR in main
Module not found: Error: Can't resolve './src' in '/home/boojum/Projects/foobar'

webpack 5.11.0 compiled with 2 errors in 167 ms
ℹ ｢wdm｣: Failed to compile.
```

This error only occurs when trying to run `webpack serve --mode development`. Production build - `webpack --mode production` - works without errors.

### For Bugs; How can we reproduce the behavior?
`npm start`

**Comment by alexander-akait** [comment]
Fixed in `webpack-dev-server@4-beta.0`

**Comment by boojum** [comment]
@alexander-akait upgrading to `webpack-dev-server@next` (4.0.0-beta.0) did not fix the issue for me:

```sh
<i> [webpack-dev-server] Project is running at http://[::]:8080/
<i> [webpack-dev-server] Content not from webpack is served from /home/boojum/Projects/playground/react-base
<e> [webpack-dev-middleware] asset main.js 257 KiB [emitted] (name: main)
<e> runtime modules 24.9 KiB 10 modules
<e> cacheable modules 196 KiB
<e>   modules by path ./node_modules/webpack-dev-server/client/ 71 KiB 12 modules
<e>   modules by path ./node_modules/html-entities/lib/*.js 61 KiB 5 modules
<e>   modules by path ./node_modules/webpack/hot/*.js 4.3 KiB 4 modules
<e>   modules by path ./node_modules/url/ 37.4 KiB 3 modules
<e>   modules by path ./node_modules/querystring/*.js 4.51 KiB
<e>     ./node_modules/querystring/index.js 127 bytes [built] [code generated]
<e>     ./node_modules/querystring/decode.js 2.34 KiB [built] [code generated]
<e>     ./node_modules/querystring/encode.js 2.04 KiB [built] [code generated]
<e>   ./node_modules/ansi-html/index.js 4.16 KiB [built] [code generated]
<e>   ./node_modules/events/events.js 13.8 KiB [built] [code generated]
<e> ./node_modules/webpack/hot/ sync nonrecursive ^\.\/log$ 170 bytes [built] [code generated]
<e> 
<e> ERROR in main
<e> Module not found: Error: Can't resolve './src' in '/home/boojum/Projects/playground/react-base'
<e> 
<e> webpack 5.11.0 compiled with 1 error in 6843 ms
<i> [webpack-dev-middleware] Failed to compile.
```

Can we reopen, please? Or should I open another issue?

**Comment by alexander-akait** [comment]
@boojum No `｢wds｣: webpack output is served from undefined`, just error what no file `src/index.js`
