### ISSUE TITLE
After installing webpack@1.13.1 globally 

### ISSUE THREAD

**Issue by DougFerron** [webpack/webpack-dev-server#541]
When I try to to do the same with webpack-dev-server I get : 
UNMET PEER DEPENDENCY webpack@1 || ^2.1.0-beta

**Comment by DougFerron** [comment]
I did but I somehow fixed the problem after removing the fish shell. I don't know why this fixed it but all seems well now.


Doug Ferron

e:  dougferron@hotmail.co.uk


________________________________

**Comment by SpaceK33z** [comment]
Cool. Could you close the issue then?

**Comment by rbeesley** [comment]
I just hit this exact problem too, but I've installed webpack@1.13.2 globally. I see the following:
```
X:\>npm install webpack -g
C:\Users\<username>\AppData\Roaming\npm\webpack -> C:\Users\<username>\AppData\Roaming\npm\node_modules\webpack\bin\webpack.js
C:\Users\<username>\AppData\Roaming\npm
`-- webpack@1.13.2

npm WARN optional Skipping failed optional dependency /webpack/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14

X:\>npm install webpack-dev-server -g
C:\Users\<username>\AppData\Roaming\npm\webpack-dev-server -> C:\Users\<username>\AppData\Roaming\npm\node_modules\webpack-dev-server\bin\webpack-dev-server.js
C:\Users\<username>\AppData\Roaming\npm
+-- UNMET PEER DEPENDENCY webpack@>=1.3.0 <3
`-- webpack-dev-server@1.14.1
  `-- UNMET PEER DEPENDENCY webpack@1 || ^2.1.0-beta

npm WARN webpack-dev-server@1.14.1 requires a peer of webpack@>=1.3.0 <3 but none was installed.
npm WARN webpack-dev-middleware@1.6.1 requires a peer of webpack@1 || ^2.1.0-beta but none was installed.

X:\>npm -v
3.10.6

X:\>node -v
v4.4.5
```

**Comment by SpaceK33z** [comment]
Could you guys try it again with `webpack-dev-server@1.15.0`? That version was just released, and should fix these issues.

**Comment by Wouter0100** [comment]
```
$ sudo npm install --global webpack
/usr/local/bin/webpack -> /usr/local/lib/node_modules/webpack/bin/webpack.js
/usr/local/lib
└── webpack@1.13.2 

npm WARN optional Skipping failed optional dependency /webpack/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
$ sudo npm install --global webpack-dev-server
/usr/local/bin/webpack-dev-server -> /usr/local/lib/node_modules/webpack-dev-server/bin/webpack-dev-server.js
/usr/local/lib
├── UNMET PEER DEPENDENCY webpack@>=1.3.0 <3
└─┬ webpack-dev-server@1.15.0 
  └── UNMET PEER DEPENDENCY webpack@1 || ^2.1.0-beta

npm WARN webpack-dev-server@1.15.0 requires a peer of webpack@>=1.3.0 <3 but none was installed.
npm WARN webpack-dev-middleware@1.6.1 requires a peer of webpack@1 || ^2.1.0-beta but none was installed.

```

Unfortunately not fixed, as it seems. Webpack is installed globally.

**Comment by dogancelik** [comment]
I installed `webpack-dev-server@1.15.1`, still not fixed

```
dogan@DOGAN-PC maker-maker
$ npm install -g webpack
C:\Users\dogan\AppData\Roaming\npm\webpack -> C:\Users\dogan\AppData\Roaming\npm\node_modules\webpack\bin\webpack.js
C:\Users\dogan\AppData\Roaming\npm
`-- webpack@1.13.2

npm WARN optional Skipping failed optional dependency /webpack/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14

dogan@DOGAN-PC maker-maker
$ npm install -g webpack-dev-server
C:\Users\dogan\AppData\Roaming\npm\webpack-dev-server -> C:\Users\dogan\AppData\Roaming\npm\node_modules\webpack-dev-server\bin\webpack-dev-server.js
C:\Users\dogan\AppData\Roaming\npm
+-- UNMET PEER DEPENDENCY webpack@>=1.3.0 <3
`-- webpack-dev-server@1.15.1
  `-- UNMET PEER DEPENDENCY webpack@1 || ^2.1.0-beta

npm WARN webpack-dev-server@1.15.1 requires a peer of webpack@>=1.3.0 <3 but none was installed.
npm WARN webpack-dev-middleware@1.6.1 requires a peer of webpack@1 || ^2.1.0-beta but none was installed.
```

**Comment by joeczucha** [comment]
Same problem here, OSX: 

    $ npm install -g webpack
    /usr/local/bin/webpack -> /usr/local/lib/node_modules/webpack/bin/webpack.js
    /usr/local/lib
    └── webpack@1.13.2

    $ npm install -g webpack-dev-server
    /usr/local/bin/webpack-dev-server -> /usr/local/lib/node_modules/webpack-dev-server/bin/webpack-dev-server.js
    /usr/local/lib
    ├── UNMET PEER DEPENDENCY webpack@>=1.3.0 <3
    └─┬ webpack-dev-server@1.15.1
      └── UNMET PEER DEPENDENCY webpack@1 || ^2.1.0-beta

    npm WARN webpack-dev-server@1.15.1 requires a peer of webpack@>=1.3.0 <3 but none was installed.
    npm WARN webpack-dev-middleware@1.6.1 requires a peer of webpack@1 || ^2.1.0-beta but none was installed.

**Comment by jerryhall** [comment]
I'm doing an entirely clean (eg 1st install ever of Webpack) and am getting this. Apologies if extraneous copy here and lack of markdown, just cutting my teeth:

C:\Users\Jerry>npm install --global webpack-dev-server
C:\Users\Jerry\AppData\Roaming\npm\webpack-dev-server -> C:\Users\Jerry\AppData\
Roaming\npm\node_modules\webpack-dev-server\bin\webpack-dev-server.js
C:\Users\Jerry\AppData\Roaming\npm
+-- UNMET PEER DEPENDENCY webpack@>=1.3.0 <3
`-- webpack-dev-server@1.15.1
  +-- compression@1.6.2
  | +-- accepts@1.3.3
  | | `-- negotiator@0.6.1
  | +-- bytes@2.3.0
  | +-- compressible@2.0.8
  | | `-- mime-db@1.23.0
  | +-- debug@2.2.0
  | | `-- ms@0.7.1
  | +-- on-headers@1.0.1
  | `-- vary@1.1.0
  +-- connect-history-api-fallback@1.3.0
  +-- express@4.14.0
  | +-- array-flatten@1.1.1
  | +-- content-disposition@0.5.1
  | +-- content-type@1.0.2
  | +-- cookie@0.3.1
  | +-- cookie-signature@1.0.6
  | +-- depd@1.1.0
  | +-- encodeurl@1.0.1
  | +-- escape-html@1.0.3
  | +-- etag@1.7.0
  | +-- finalhandler@0.5.0
  | | +-- statuses@1.3.0
  | | `-- unpipe@1.0.0
  | +-- fresh@0.3.0
  | +-- merge-descriptors@1.0.1
  | +-- methods@1.1.2
  | +-- on-finished@2.3.0
  | | `-- ee-first@1.1.1
  | +-- parseurl@1.3.1
  | +-- path-to-regexp@0.1.7
  | +-- proxy-addr@1.1.2
  | | +-- forwarded@0.1.0
  | | `-- ipaddr.js@1.1.1
  | +-- qs@6.2.0
  | +-- range-parser@1.2.0
  | +-- send@0.14.1
  | | `-- destroy@1.0.4
  | +-- serve-static@1.11.1
  | +-- type-is@1.6.13
  | | `-- media-typer@0.3.0
  | `-- utils-merge@1.0.0
  +-- http-proxy-middleware@0.17.1
  | +-- http-proxy@1.14.0
  | | +-- eventemitter3@1.2.0
  | | `-- requires-port@1.0.0
  | +-- is-glob@2.0.1
  | | `-- is-extglob@1.0.0
  | +-- lodash@4.15.0
  | `-- micromatch@2.3.11
  |   +-- arr-diff@2.0.0
  |   | `-- arr-flatten@1.0.1
  |   +-- array-unique@0.2.1
  |   +-- braces@1.8.5
  |   | +-- expand-range@1.8.2
  |   | | `-- fill-range@2.2.3
  |   | |   +-- is-number@2.1.0
  |   | |   +-- isobject@2.1.0
  |   | |   +-- randomatic@1.1.5
  |   | |   `-- repeat-string@1.5.4
  |   | +-- preserve@0.2.0
  |   | `-- repeat-element@1.1.2
  |   +-- expand-brackets@0.1.5
  |   | `-- is-posix-bracket@0.1.1
  |   +-- extglob@0.3.2
  |   +-- filename-regex@2.0.0
  |   +-- kind-of@3.0.4
  |   | `-- is-buffer@1.1.4
  |   +-- normalize-path@2.0.1
  |   +-- object.omit@2.0.0
  |   | +-- for-own@0.1.4
  |   | | `-- for-in@0.1.5
  |   | `-- is-extendable@0.1.1
  |   +-- parse-glob@3.0.4
  |   | +-- glob-base@0.3.0
  |   | | `-- glob-parent@2.0.0
  |   | `-- is-dotfile@1.0.2
  |   `-- regex-cache@0.4.3
  |     +-- is-equal-shallow@0.1.3
  |     `-- is-primitive@2.0.0
  +-- open@0.0.5
  +-- optimist@0.6.1
  | +-- minimist@0.0.10
  | `-- wordwrap@0.0.3
  +-- serve-index@1.8.0
  | +-- batch@0.5.3
  | +-- http-errors@1.5.0
  | | `-- setprototypeof@1.0.1
  | `-- mime-types@2.1.11
  +-- sockjs@0.3.17
  | +-- faye-websocket@0.10.0
  | | `-- websocket-driver@0.6.5
  | |   `-- websocket-extensions@0.1.1
  | `-- uuid@2.0.2
  +-- sockjs-client@1.1.1
  | +-- eventsource@0.1.6
  | | `-- original@1.0.0
  | |   `-- url-parse@1.0.5
  | +-- faye-websocket@0.11.0
  | +-- inherits@2.0.1
  | +-- json3@3.3.2
  | `-- url-parse@1.1.3
  |   `-- querystringify@0.0.4
  +-- stream-cache@0.0.2
  +-- strip-ansi@3.0.1
  | `-- ansi-regex@2.0.0
  +-- supports-color@3.1.2
  | `-- has-flag@1.0.0
  +-- UNMET PEER DEPENDENCY webpack@1 || ^2.1.0-beta
  `-- webpack-dev-middleware@1.6.1
    +-- memory-fs@0.3.0
    | +-- errno@0.1.4
    | | `-- prr@0.0.0
    | `-- readable-stream@2.1.5
    |   +-- buffer-shims@1.0.0
    |   +-- core-util-is@1.0.2
    |   +-- isarray@1.0.0
    |   +-- process-nextick-args@1.0.7
    |   +-- string_decoder@0.10.31
    |   `-- util-deprecate@1.0.2
    `-- mime@1.3.4

npm WARN webpack-dev-server@1.15.1 requires a peer of webpack@>=1.3.0 <3 but non
e was installed.
npm WARN webpack-dev-middleware@1.6.1 requires a peer of webpack@1 || ^2.1.0-bet
a but none was installed.

C:\Users\Jerry>

**Comment by SpaceK33z** [comment]
So do you still have this issue when you don't install it globally? You should not install these packages globally.

In my own tests, it seems to work when installing it in a project, but I get the same error when using it globally. That doesn't really sound like an issue I can fix in webpack-dev-server.

**Comment by SpaceK33z** [comment]
If you really want to install it globally, putting everything on one line seems to work: `npm install -g webpack webpack-dev-server`.

Closing this since now I'm sure I can't do anything about this issue in dev-server.

**Comment by doudounannan** [comment]
I also have this issue.I install globally webpack & webpack-dev-server ,but it still occurs "npm WARN webpack-dev-server@1.15.0 requires a peer of webpack@>=1.3.0 <3 but none was installed".
How to solve this issue?
