### ISSUE TITLE
self.postMessage is not a function under webpack-dev-server

### ISSUE THREAD

**Issue by didi0613** [webpack/webpack-dev-server#792]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
<img width="520" alt="screen shot 2017-02-16 at 6 27 48 pm" src="https://cloud.githubusercontent.com/assets/10135897/23050226/d1477524-f475-11e6-9264-f494500d244d.png">
<img width="1031" alt="screen shot 2017-02-16 at 6 27 56 pm" src="https://cloud.githubusercontent.com/assets/10135897/23050229/d4b86e5c-f475-11e6-9183-2073a45b443c.png">
Self is referring to a wrong object `serviceworkerglobalscope` instead of `window`.
PostMessage is not defined under `serviceworkerglobalscope`

**If the current behavior is a bug, please provide the steps to reproduce.**

Clone https://github.com/didi0613/electrode/tree/webpack-2.0
checkout branch webpack-2.0
npm i && npm run bootstrap
goto samples/universal-react-node app
npm install
gulp dev

**What is the expected behavior?**
There should be no error and pwa should work

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention your webpack and Operating System version.**
webpack 2.2.0
wepack-dev-server 2.2.0
os: mac

**Comment by dangerousdan** [comment]
Related to #745

**Comment by hccde** [comment]
I've found out how this bug is happening,it's not easy,this is because we use `iframe.postMessage` to refresh.But unfortunately, in the `Worker` there is also a method called `postMessage` ,that's ` self.postMessage ` .When ' worker.js'  as an entry in 'webpack.config.js',usually we have to do that,'worker.js' will be packaged with 'webpack-dev-server/client',As previously mentioned，we use 'iframe.postMessage' to refresh，in code,that's:
`                   if(typeof self !== "undefined") {
			// broadcast update to window
			self.postMessage("webpackHotUpdate" + currentHash, "*");
		     }`
'worker.js'  which is packaged with 'webpack-dev-server/client' also contains this code, pay attention, at this time,  `self` is not `window`  but `[DedicatedWorkerGlobalScope](https://developer.mozilla.org/en-US/docs/Web/API/Worker/postMessage)`,this is the key point. 'webworker' is in a special context  different from 'window'.so we need to distinguish between these two objects.And i have initiated a 'pr' to fix this. #813

**Comment by shellscape** [comment]
Should be resolved in #813 and v2.7.1. If it's not, please ping me and we'll reopen.

**Comment by ddomonkos** [comment]
Hi @shellscape, I still have the error in v2.7.1. Do you have any tips how to fix this?

![image](https://user-images.githubusercontent.com/3531139/29920949-249561a4-8e50-11e7-8e23-d5d2199e8336.png)

Let me know if you need more info about the error.

**Comment by shellscape** [comment]
Unfortunately I don't. We've had a few PRs related to this and I'm unable to reproduce the issue in any of our tests. If this is still occurring there's a better than average chance that it's your configuration or environment causing it. Sidenote: If you're not on webpack@3 yet, it's time to upgrade.

**Comment by ddomonkos** [comment]
Ok thank you, I'll try to debug it some more, maybe I find something.

Btw I am using the newest webpack already.

**Comment by codelinguist** [comment]
I also had this exact issue in my angular 4 app today
This occurs when i call a function that opens a WebSocket connection and sends message when the app initializes.
I thought there's some contention happening so i moved the function call inside setTimeout with 100ms delay to give time for the webpack dev server to initialize. The error is gone!

I hope this helps.

**Comment by DustinArmstrong** [comment]
Sorry for bringing this thread back to life, but I've been dealing with this problem for a few days now on Webpack 3, and think I've narrowed it down to at least one possible solution for anyone having problems.

In my Vue project I was submitting Ajax requests from a component. In order to maintain access to update data tied to `this` further up in my component I used `self = this` to pass to my function. I missed the `var` definition in my markup, and Webpack's `self.postMessage` was trying to access my Vue data instead.

No errors were presented on compilation since `self` was already defined as a variable in Webpack.

**Comment by shellscape** [comment]
@DustinArmstrong that may be something the main webpack project can assist with - perhaps a console warning or some such.

**Comment by YDJSZY** [comment]
I have also this problem, I don't know how to do ...

**Comment by ereztdev** [comment]
Yup, same here.
Returning data from a computed function:

```
computed:{

            boom(){

                setTimeout(funky, 4000);
                function funky() {
                    self = this;
                    return self.$store.getters.cityNames
                }
            }
        }
```

**Comment by devilsbibble** [comment]
Do you have set `window.self=xxx` ?  Delete it .

**Comment by ereztdev** [comment]
just don't use self, use `that = this`, or any other var that would not be `self`

**Comment by imam** [comment]
If you want to use `self` anywhere in your code, make sure you always redefined `self` at the very last line of everything (`window.self = window`)

**Comment by asrofie** [comment]
I have same issue, I fixed it with finding `self` variable and make sure it redefined (using `let` keyword, e.g `let self = this`).

**Comment by martinsJoseph007** [comment]
> Sorry for bringing this thread back to life, but I've been dealing with this problem for a few days now on Webpack 3, and think I've narrowed it down to at least one possible solution for anyone having problems.
> 
> In my Vue project I was submitting Ajax requests from a component. In order to maintain access to update data tied to `this` further up in my component I used `self = this` to pass to my function. I missed the `var` definition in my markup, and Webpack's `self.postMessage` was trying to access my Vue data instead.
> 
> No errors were presented on compilation since `self` was already defined as a variable in Webpack.

You are genius.........

**Comment by theWebalyst** [comment]
I was having this issue with webpack dev server in my Svelte project even though I was using `const self = this`. Changing `const self` to `const me` seems to have fixed it.
