### ISSUE TITLE
Error: addMembership ENODEV - Using It Without Network Connection with Loopback Interface At localhost/127.0.0.1

### ISSUE THREAD

**Issue by idnesdotlink** [webpack/webpack-dev-server#979]
**Do you want to request a *feature* or report a *bug*?**
BUG Maybe

**What is the current behavior?**

**Error With Trace**
`Error: addMembership ENODEV
    at exports._errnoException (util.js:1018:11)
    at Socket.addMembership (dgram.js:506:11)
    at Socket.<anonymous> (/home/idnes/BlaBlaBla/node_modules/multicast-dns/index.js:53:16)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at startListening (dgram.js:121:10)
    at _handle.lookup (dgram.js:226:7)
    at _combinedTickCallback (internal/process/next_tick.js:83:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
`

**If the current behavior is a bug, please provide the steps to reproduce.**
Fresh Install - Simple Configuration

**CASE A : NOT WORK** 
- node 6.11.0
- npm 5.1.0
- webpack 3.1.0
- webpack-dev-server 2.5.0 and 2.5.1
- using loopback interface at localhost / 127.0.0.1
- NO NETWORK CONNECTED !!

**CASE B: WORK** 
- node 6.11.0
- npm 5.1.0
- webpack 3.1.0
- webpack-dev-server 2.5.0 and 2.5.1
- using loopback interface at localhost / 127.0.0.1
- WITH NETWORK CONNECTED !!

**CASE C: WORK** 
- node 6.11.0
- npm 5.1.0
- webpack 3.1.0
- webpack-dev-server 2.4.5
- using loopback interface at localhost / 127.0.0.1
- NO NETWORK CONNECTED !!

**What is the expected behavior?**
 No Error

**If this is a feature request, what is motivation or use case for changing the behavior?**
- Sometimes i work without network connection at all
- It work before 2.5.0 

**Please mention your webpack and Operating System version.**
ubuntu 16.04

**Comment by Plazmaz** [comment]
Is that the full stack trace?

**Comment by idnesdotlink** [comment]
@Plazmaz i updated my issues ..

**Comment by bneumann** [comment]
Same for me. I was trying to work offline and got the same error as @idnesdotlink. When I open my hotspot everything works again. Seems that webpack-dev-server requires to be online to work.

Workaround: Go online, start webpack-dev-server, go offline. It builds and refreshes just fine. Restarting the server however results in the error again

**Comment by kimat** [comment]
- when starting the webpack-dev-server when wifi on : 

```
> webpack-dev-server --env.dev
Project is running at http://localhost:8080/
```

- when wifi is off:

```
> webpack-dev-server --env.dev

events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: addMembership ENODEV
    at exports._errnoException (util.js:1016:11)
    at Socket.addMembership (dgram.js:579:11)
    at Socket.<anonymous> (/home/home/my/react/outliner/node_modules/multicast-dns/index.js:53:16)
    at emitNone (events.js:110:20)
    at Socket.emit (events.js:207:7)
    at startListening (dgram.js:144:10)
    at _handle.lookup (dgram.js:249:7)
    at _combinedTickCallback (internal/process/next_tick.js:105:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
    at Function.Module.runMain (module.js:607:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! outliner@0.0.1 dev: `webpack-dev-server --env.dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the outliner@0.0.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

**Comment by abou7mied** [comment]
Same for me node **6.11.0**, webpack-dev-server **2.5.1** webpack **2.6.1**

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: addMembership ENODEV
    at exports._errnoException (util.js:1018:11)
    at Socket.addMembership (dgram.js:506:11)
    at Socket.<anonymous> (node_modules/multicast-dns/index.js:53:16)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at startListening (dgram.js:121:10)
    at _handle.lookup (dgram.js:226:7)
    at _combinedTickCallback (internal/process/next_tick.js:83:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3

npm ERR! Linux 4.8.0-58-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/bin/npm-cli.js" "run" "webpack-dev-server" "--scripts-prepend-node-path=auto"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! app@1.0.0 webpack-dev-server: `webpack-dev-server --watch --hot --colors`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the app@1.0.0 webpack-dev-server script 'webpack-dev-server --watch --hot --colors'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --watch --hot --colors
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     npm-debug.log

Process finished with exit code 1
```

**Comment by Plazmaz** [comment]
Have you tried building from source? There was a similar issue fixed in #958

**Comment by ai** [comment]
I use latest webpack and still have this issue when I work in airplane

```
Error: addMembership ENODEV
    at exports._errnoException (util.js:1050:11)
    at Socket.addMembership (dgram.js:502:11)
    at Socket.<anonymous> (/home/ai/Dev/logux-status/node_modules/multicast-dns/index.js:53:16)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:188:7)
    at startListening (dgram.js:117:10)
    at _handle.lookup (dgram.js:222:7)
    at _combinedTickCallback (internal/process/next_tick.js:83:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
```

with config:

```js
  devServer: {
    contentBase: path.join(__dirname, 'build')
  }
```

**Comment by ai** [comment]
@Plazmaz I tested webpack’s `master` and #958 fix this problem.

What blocks releasing #958?

**Comment by Plazmaz** [comment]
I don't know @ai, I tried PRing a version bump, but they refused to accept it from someone without collaborator access.

**Comment by ai** [comment]
@Plazmaz oops, I thought you were from core team :D.

@TheLarkInn What blocks releasing #958? Because of this issue, it is hard to write code in the most productive time — during airplane flight :D.

**Comment by roonyh** [comment]
`npm upgrade webpack-dev-server` fixed the issue for me.  

Its fixed in `2.6.1`

**Comment by idnesdotlink** [comment]
closing it with 2.6.1 update

**Comment by kimat** [comment]
This is still broken for me : when I try to start `webpack-dev-server` with wifi off : 

```json
"webpack": "^3.4.1",
"webpack-dev-server": "^2.6.1"
```

```

events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: addMembership ENODEV
    at exports._errnoException (util.js:1016:11)
    at Socket.addMembership (dgram.js:579:11)
    at Socket.<anonymous> (/.../node_modules/multicast-dns/index.js:53:16)
    at emitNone (events.js:110:20)
    at Socket.emit (events.js:207:7)
    at startListening (dgram.js:144:10)
    at _handle.lookup (dgram.js:249:7)
    at _combinedTickCallback (internal/process/next_tick.js:105:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
    at Function.Module.runMain (module.js:607:11)
```

**Comment by Gadrawingz** [comment]
I'm using we pack up inside my nodejs project but it is not working, and I'm getting error but from internal libraries In connection with WebSocket handshake, is there any relationship between them?? How to resolve??
